### ISSUE TITLE
Microverse Final Capstone: Kanban Board

### ISSUE THREAD

**Issue by Shisui6** [Shisui6/vesper-backend#16]
## Details 🔬
- No of team members: 4
- Link to project: [link](https://github.com/users/Shisui6/projects/1)
- Link to frontend repo: [link](https://github.com/Shisui6/car-rental-front-end)
- Team members: @Shisui6, @zakiyousufi, @Sonickmumba and @UsirusenIkon

## Screenshot 📷
<img width="960" alt="image" src="https://user-images.githubusercontent.com/37116322/229125297-dc1b0187-e3b0-4c52-a8f4-4f01c143cf6c.png">

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 

## Highlights
- Met minimum requirements 👍 

## Optional suggestions
- Consider adding labels to help distinguish types of tasks/issues
- Consider putting more realistic weights to your tasks

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.


Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
